#!/usr/bin/env sh

partition_selection=$(
  lsblk --list --output Name,path,size,label,hotplug,mountpoint \
  | grep -E '1 $' \
  | grep -E '^[a-z]+[0-9]' \
  | sed 's/1 $//'
)

# Checking if the selection is a partition or a the full drive
# while echo "${partition_selection}" | grep -q --extended-regexp '^[a-z]' ; do
#   echo "Select a partition inside a drive, not the full drive."
#   sleep 2
#   partition_selection=$(lsblk --output Name,path,size,label | \
#                         fzf --reverse --header="Pick a partition") 
# done
#

if [[ -z "${partition_selection}"  ]]; then 
  echo "No usb device found"
  sleep 1.5
  exit
fi

partition_selection=$(
  echo "${partition_selection}" \
  | fzf --reverse --header="Pick block device"
)


partition_path=$(echo "$partition_selection" | awk '{print$2}')

if [[ -z "${partition_path}" ]]; then
  exit
fi


if ! udisksctl mount -b "${partition_path}" ; then
  # Give time to show error message
  sleep 2
fi
